### ISSUE TITLE
Sourcing Code Pro: adapt Source Code Pro for SugarTeX and tune fallback fonts

### ISSUE THREAD

**Issue by kiwi0fruit** [kiwi0fruit/open-fonts#7]
* [x] Some spaces are of wrong width - not monospace: ~apply monospacifier to all styles. After that check how combining characters work: start with localfonts.eu~, ~*Delete them*~, fill them with common space char.
* [x] Fix broken `∕` (division slash) (simply delete it)
* [x] Do not take thin styles
* [x] Fallbacks monospacified for Roboto Mono can be used

**Comment by kiwi0fruit** [comment]
```css
@font-face {
  font-family: 'Linux Libertine Math';
  src: local("Libertinus Serif");
  font-weight: normal;
  font-style: normal;
}
@font-face {
  font-family: 'Linux Libertine Math';
  src: local("Libertinus Serif BBold");
  font-weight: bold;
  font-style: normal;
}
@font-face {
  font-family: 'Linux Libertine Math';
  src: local("STIX Two Text IItalic");
  font-weight: normal;
  font-style: italic;
}
@font-face {
  font-family: 'Linux Libertine Math';
  src: local("STIX Two Text BBoldIt");
  font-weight: bold;
  font-style: italic;
}
```
